# Generated by Django 6.0.4 on 2026-04-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Company name (e.g., Grameenphone Ltd.)', max_length=200, unique=True)),
                ('sector', models.CharField(choices=[('Telecom', 'Telecommunications'), ('Banking', 'Banking & Finance'), ('Pharmaceuticals', 'Pharmaceuticals'), ('Energy', 'Energy'), ('Retail', 'Retail & Commerce'), ('Manufacturing', 'Manufacturing'), ('Technology', 'Technology'), ('Textiles', 'Textiles'), ('Consumer', 'Consumer Goods'), ('Agro', 'Agriculture'), ('Real Estate', 'Real Estate'), ('Other', 'Other')], help_text='Primary business sector', max_length=50)),
                ('logo_url', models.URLField(blank=True, help_text='URL to company logo image', null=True)),
                ('headquarters', models.CharField(help_text='Headquarters location (e.g., Dhaka, Bangladesh)', max_length=200)),
                ('founded', models.IntegerField(help_text='Year company was founded')),
                ('description', models.TextField(blank=True, help_text='Brief description of the company and its business', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created in the system')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['-created_at'],
            },
        ),
    ]
