# Generated by Django 6.0.4 on 2026-04-11 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='EdTech startup name', max_length=200, unique=True)),
                ('sector', models.CharField(help_text='EdTech sectors (e.g., K-12, test prep, upskilling)', max_length=200)),
                ('founders', models.CharField(help_text='Founder name(s)', max_length=300)),
                ('logo_url', models.URLField(blank=True, help_text='URL to startup logo image', null=True)),
                ('headquarters', models.CharField(help_text='Headquarters location', max_length=200)),
                ('year_founded', models.IntegerField(help_text='Year startup was founded')),
                ('total_funding', models.CharField(blank=True, help_text='Total funding received (e.g., $9.26M)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created in the system')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
            ],
            options={
                'verbose_name': 'EdTech Startup',
                'verbose_name_plural': 'EdTech Startups',
                'ordering': ['-created_at'],
            },
        ),
    ]
